ldd-alt:
  description: |
    The Alternate dictionary contains classes that describe sets of data values which are interchangeable with each other.
ldd-ama:
  name: "Atmospheres Modeling Annex"
  description: |
    The AMA dictionary provides attributes appropriate to atmospheric modeling products that will reside in the Atmospheres Modeling Annex.
ldd-cart:
  description: |
    The Cartography Dictionary contains classes, elements, attributes, and rules describing map projections, including both cartographic and lander related definitions and descriptions. The PDS Cartography dictionary is based on and utilizes the existing Federal Geographic Data Committee (FGDC) Content Standard for Digital Geospatial Metadata, with modifications and extensions applied by PDS as needed for planetary mapping application.
ldd-ctli:
  name: "Context Type List: Instrument"
  description: |
    The CTLI dictionary provides a set of type values for instruments for use in instrument context products.
ldd-disp:
  description: |
    The Display dictionary contains classes, attributes, and rules for specifying how arrays (images) as stored, should be displayed to users. For example, defining the vertical display direction 'Bottom to Top' or horizontal direction 'Left to Right' and it can provide guidance on mapping multiband arrays for color display (red, green, and blue) or as a movie sequence (video).
ldd-ebt:
  name: "Earth-Based Telescope"
  description: |
    The Earth-Based Telescope dictionary contains classes, attributes, and rules for specifying the metadata associated with observing parameters, provenance, and geometry relevant to ground-based telescopes on Earth and for Earth-orbiting (or Lagrange point) telescopes.
ldd-exo:
  description: |
    The exoPlanet dictionary (namespace: exo) contains classes, attributes, and rules for specifying metadata associated with exoPlanet stars and planets. The dictionary can provide guidance on mapping multiband arrays.
ldd-geom:
  description: |
    The Geometry dictionary contains classes, attributes, and rules for specifying the geometry parameters associated with science observations.
ldd-img:
  description: |
    The Imaging dictionary contains classes, attributes, and rules for specifying the metadata associated with imaging and spectrometer data products.
ldd-ml:
  name: "Machine Learning Analysis"
  description: |
    The Machine Learning Analysis dictionary defines classes and attributes used to describe products generated by machine learning methods applied to PDS data. This information provides traceability for product provenance and credit to the creators.
ldd-msn:
  description: |
    The sub-dictionary for the Mission Information class namespace.
ldd-msss_cam_mh:
  description: |
    This dictionary is for a class of cameras developed by Malin Space Science Systems (MSSS) that share a common architecture or digital electronics assembly. Example cameras include Mastcam, MAHLI, MARDI, Mastcam-Z, SHERLOC-Watson and SHERLOC-ACI
ldd-multi:
  name: Multidimensional
  description: |
    The Multi dictionary contains classes that describe the composition of multidimensional data consisting of Array (and Array subclass) data objects. It provides a way to associated data objects and align the objects in general multi-dimensional structures.
ldd-nucspec:
  name: "Nuclear Spectroscopy"
  description: |
    The Nuclear Spectroscopy dictionary provides classes, attributes, and rules for describing the circumstances surrounding nuclear spectroscopy observations.
ldd-particle:
  description: |
    The Particle dictionary contains attributes that may be used to help identify particle parameters included in a PDS4 product to supplement the information provided in the Primary_Result_Summary and in order to support enhanced data discovery.
ldd-proc:
  description: |
    The Processing_Information Dictionary contains detailed information regarding the history of processing performed on data product(s) in order to produce the current product.
ldd-radar:
  name: Radar
  description: |
    The Radar dictionary describes the circumstances surrounding radar observations.
ldd-rings:
  name: Rings
  description: |
    The Rings dictionary contains classes supporting planetary ring observations including ring-specific geometric parameters.
ldd-sb:
  name: Small Bodies
  description: |
    This dictionary will provide classes to support the documentation, support, discovery, and reuse of data from, by, and for small bodies research.
ldd-spectral:
  name: Spectral
  description: |
    The Spectral (sp) discipline dictionary contains classes for defining the spectral bin characteristics (in wavelength, frequency, or wave number) of a data product.
ldd-speclib:
  description: |
    The Spectral Library data dictionary defines the metadata terms that describe laboratory spectral measurements, including classification of the samples measured.
ldd-img_surface:
  description: |
    The Surface Imaging dictionary contains classes, attributes, and rules for specifying the metadata associated with imaging and spectrometer data products of surface missions.
ldd-msn_surface:
  description: |
    The Surface Mission dictionary contains classes, attributes, and rules for specifying metadata elements which are specific to the data products of surface missions but are common among multiple such missions.
ldd-survey:
  description: |
    The Survey dictionary provides classes, attributes, and rules for describing the circumstances surrounding sky survey observations.
ldd-wave:
  description: |
    The Wave dictionary contains classes that describe the composition of multidimensional wave data consisting of Array (and Array subclass) data objects.
