name: "[data-release] PDS Data Release - Lead Node Announcement"
description: Issue for Lead Node only to provide main body of release announcement text.
title: '[ANNOUNCE] <mission_name> Release <release_number>'
labels: "data-release,p.must-have,sprint-backlog"
assignees: rchenatjpl
projects: "NASA-PDS/19"

body:

  - type: input
    attributes:
      label: "Title of Release"
      description: "The email subject of the release announcement."
    validations:
      required: true

  - type: input
    attributes:
      label: "Applicable Investigation(s)"
      description: "PDS4 Context LID(s) or PDS3 MISSION_NAME(s) of investigation that are relevant to the release"
    validations:
      required: true

  - type: input
    attributes:
      label: "Release Number (or ID)"
      description: "Release number or identifier."
    validations:
      required: true

  - type: input
    attributes:
      label: "Actual Release Date"
      description: "When this data will go public."
    validations:
      required: true

  - type: input
    attributes:
      label: "Anticipated Release Date"
      description: "Anticipated Release Date according to the data release calendar."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Release Announcement"
      description: "Main body of release announcement. Be sure to include any information about delayed or missing data"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: "Applicable Data Release Issues"
      description: "Links to the data release issues in GitHub applicable to this data release announcement."


  - type: textarea
    attributes:
      label: "Any Additional Information"
      description: "Please provide any additional context or files that may be relevant for this release."


  - type: markdown
    attributes:
      value: |
        ## For Internal EN Operations Team To Complete

  - type: checkboxes
    attributes:
      label: Data Release Checklist
      options:
        - label: Ingest into legacy registry
        - label: Create data release announcement web page
        - label: Send out data release announcement to subscribers
