name: "[doi] Release a DOI"
description: Release a DOI for a bundle, collection, or other PDS4 product.
title: '[doi] Release DOI: <some identifying info here>'
labels: "doi.release,p.must-have,sprint-backlog"
assignees: rsjoyner
projects: "NASA-PDS/19"

body:

  - type: markdown
    attributes:
      value: "## Pre-requisites"

  - type: markdown
    attributes:
      value: |
         **If you have reserved a DOI, you must have:**
           * updated the product metadata with the DOI
           * put the data online
           * sent the PDS4 labels to EN
           * EN has completed registering the data
        
         **If you have legacy PDS4 data that has already been registered with EN**
           * no additional prerequisite needed

  - type: checkboxes
    attributes:
      label: Confirm Pre-requisites
      options:
        - label: I confirm the **request is to mint an "active / findable" DOI using the same previously reserved DOI**
          required: true
        - label: I confirm the **the previously "reserved" DOI has been added to the product labels** (where applicable)
          required: true
        - label: I confirm the **data is available online**
          required: true
        - label: I confirm the **the data has been released through EN legacy registry**
          required: true
        - label: I confirm **the data has been loaded into our Node Registry and is searchable through the API**
          required: true

  - type: dropdown
    id: node
    attributes:
      label: Requesting Node
      description: The Node requesting the DOI
      multiple: false
      options:
        - "ATM"
        - "ENG"
        - "GEO"
        - "IMG"
        - "NAIF"
        - "PPI"
        - "RS"
        - "RINGS"
        - "SBN"
    validations:
      required: yes

  - type: textarea
    attributes:
      label: "Identifiers"
      description: "List of LIDVIDs and their associated DOIs to be released"
      placeholder: |
        lidvid_1 - doi_1
        lidvid_2 - doi_2
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Product Labels"
      description: |
        Either attach a ZIP of all the PDS4 labels associated with the DOIs to-be-released, or provide
        URLs.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Any Additional Information"
      description: "Please provide any additional context or files that may be relevant for this release."
