name: "[doi] Reserve a DOI"
description: Reserve a DOI while you are preparing your PDS4 labels prior to release.
title: '[doi] Reserve DOI: <some identifying info here>'
labels: "doi.reserve,p.must-have,sprint-backlog"
assignees: rsjoyner
projects: "NASA-PDS/19"

body:

  - type: checkboxes
    attributes:
      label: Confirm Pre-requisites
      options:
        - label: "I confirm I have **checked the PDS DOI Search** and there is no permutation of this product LID(s) that has had a DOI reserved or released previously."
          required: true

  - type: dropdown
    id: node
    attributes:
      label: Requesting Node
      description: The Node requesting the DOI
      multiple: false
      options:
        - "ATM"
        - "ENG"
        - "GEO"
        - "IMG"
        - "NAIF"
        - "PPI"
        - "RS"
        - "RINGS"
        - "SBN"
    validations:
      required: yes

  - type: textarea
    attributes:
      label: "Identifiers"
      description: "List of LIDVIDs of products to reserve DOIs (separate with newlines)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "DOI Reserve Spreadsheet"
      description: |
        Attach your completed spreadsheet template: https://github.com/NASA-PDS/doi-service/raw/refs/heads/main/docs/operations/DOI_reserve_template.xlsx

        Tip: You can drag and drop files into the text box below.

    validations:
      required: true

  - type: textarea
    attributes:
      label: "Any Additional Information"
      description: "Please provide any additional context or files that may be relevant for this release."
